#!/usr/bin/env node

/**
 * Config Injection Script
 *
 * This script injects API endpoint URLs into the frontend configuration
 * by reading CloudFormation outputs and updating the endpoints.ts file.
 *
 * Usage:
 *   node scripts/inject-config.js [environment]
 *
 * Or with explicit URLs:
 *   BUCKETING_API_URL=https://... RECOMMENDER_API_URL=https://... node scripts/inject-config.js
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const environment = process.argv[2] || 'dev';
const componentName = 'aws-ml-platform';

console.log(`\n📦 Injecting configuration for environment: ${environment}\n`);

// Try to get URLs from environment variables first
let bucketingApiUrl = process.env.BUCKETING_API_URL;
let recommenderApiUrl = process.env.RECOMMENDER_API_URL;
let region = process.env.AWS_REGION || 'eu-west-1';

// If not provided, try to fetch from CloudFormation
if (!bucketingApiUrl || !recommenderApiUrl) {
  console.log('🔍 Fetching API URLs from CloudFormation outputs...');

  try {
    // Get bucketing API URL
    const bucketingStackName = `${componentName}-ExperimentPipeline-${environment}`;
    const bucketingOutput = execSync(
      `aws cloudformation describe-stacks --stack-name ${bucketingStackName} --query "Stacks[0].Outputs[?contains(OutputKey, 'api-url')].OutputValue" --output text`,
      { encoding: 'utf-8' }
    ).trim();

    if (bucketingOutput && !bucketingOutput.includes('error')) {
      bucketingApiUrl = bucketingOutput;
      console.log(`  ✓ Bucketing API: ${bucketingApiUrl}`);
    }
  } catch (err) {
    console.log('  ⚠ Could not fetch bucketing API URL from CloudFormation');
  }

  try {
    // Get recommender API URL
    const recommenderStackName = `${componentName}-RecommenderPipeline-${environment}`;
    const recommenderOutput = execSync(
      `aws cloudformation describe-stacks --stack-name ${recommenderStackName} --query "Stacks[0].Outputs[?contains(OutputKey, 'api-url')].OutputValue" --output text`,
      { encoding: 'utf-8' }
    ).trim();

    if (recommenderOutput && !recommenderOutput.includes('error')) {
      recommenderApiUrl = recommenderOutput;
      console.log(`  ✓ Recommender API: ${recommenderApiUrl}`);
    }
  } catch (err) {
    console.log('  ⚠ Could not fetch recommender API URL from CloudFormation');
  }
}

// Set defaults if still not available
if (!bucketingApiUrl) {
  bucketingApiUrl = '__BUCKETING_API_URL__';
  console.log('  ℹ Using placeholder for bucketing API URL');
}

if (!recommenderApiUrl) {
  recommenderApiUrl = '__RECOMMENDER_API_URL__';
  console.log('  ℹ Using placeholder for recommender API URL');
}

// Update the config file
const configPath = path.join(__dirname, '../src/config/endpoints.ts');
const configContent = `/**
 * API Configuration
 * 
 * This file is auto-generated by the CDK stack during deployment.
 * The values will be replaced with the actual API Gateway URLs.
 * 
 * Generated: ${new Date().toISOString()}
 * Environment: ${environment}
 */

export interface ApiConfig {
  bucketingApiUrl: string;
  recommenderApiUrl: string;
  environment: string;
  region: string;
}

// Configuration - auto-generated during build
export const apiConfig: ApiConfig = {
  bucketingApiUrl: '${bucketingApiUrl}',
  recommenderApiUrl: '${recommenderApiUrl}',
  environment: '${environment}',
  region: '${region}',
};

/**
 * Check if running in development mode with placeholder URLs
 */
export function isConfigured(): boolean {
  return !apiConfig.bucketingApiUrl.startsWith('__') && 
         !apiConfig.recommenderApiUrl.startsWith('__');
}

/**
 * Get the full URL for the bucketing endpoint
 */
export function getBucketingUrl(): string {
  return \`\${apiConfig.bucketingApiUrl}bucket\`;
}

/**
 * Get the full URL for the recommender endpoint
 */
export function getRecommenderUrl(): string {
  return \`\${apiConfig.recommenderApiUrl}recommend\`;
}
`;

fs.writeFileSync(configPath, configContent);
console.log(`\n✅ Configuration written to: ${configPath}\n`);
