/**
 * API Configuration
 *
 * This file is auto-generated by the CDK stack during deployment.
 * The values will be replaced with the actual API Gateway URLs.
 */

export interface ApiConfig {
  bucketingApiUrl: string;
  recommenderApiUrl: string;
  environment: string;
  region: string;
}

// Default configuration - will be overwritten during deployment
export const apiConfig: ApiConfig = {
  bucketingApiUrl: '__BUCKETING_API_URL__',
  recommenderApiUrl: '__RECOMMENDER_API_URL__',
  environment: '__ENVIRONMENT__',
  region: '__REGION__',
};

/**
 * Check if running in development mode with placeholder URLs
 */
export function isConfigured(): boolean {
  return (
    !apiConfig.bucketingApiUrl.startsWith('__') &&
    !apiConfig.recommenderApiUrl.startsWith('__')
  );
}

/**
 * Get the full URL for the bucketing endpoint
 */
export function getBucketingUrl(): string {
  return `${apiConfig.bucketingApiUrl}bucket`;
}

/**
 * Get the full URL for the recommender endpoint
 */
export function getRecommenderUrl(): string {
  return `${apiConfig.recommenderApiUrl}recommend`;
}
