/**
 * API Configuration
 *
 * This file is auto-generated by the CDK stack during deployment.
 * The values will be replaced with the actual API Gateway URLs.
 */

export interface ApiConfig {
  bucketingApiUrl: string;
  recommenderApiUrl: string;
  bucketingApiKey: string;
  recommenderApiKey: string;
  environment: string;
  region: string;
}

export const apiConfig: ApiConfig = {
  bucketingApiUrl: '__BUCKETING_API_URL__',
  recommenderApiUrl: '__RECOMMENDER_API_URL__',
  bucketingApiKey: '__BUCKETING_API_KEY__',
  recommenderApiKey: '__RECOMMENDER_API_KEY__',
  environment: '__ENVIRONMENT__',
  region: '__REGION__',
};

export function isConfigured(apiType?: 'bucketing' | 'recommender'): boolean {
  const bucketingReady = !apiConfig.bucketingApiUrl.startsWith('__');
  const recommenderReady = !apiConfig.recommenderApiUrl.startsWith('__');

  if (!apiType) {
    return bucketingReady && recommenderReady;
  }

  return apiType === 'bucketing' ? bucketingReady : recommenderReady;
}

export function getBucketingUrl(): string {
  return `${apiConfig.bucketingApiUrl}bucket`;
}

export function getRecommenderUrl(): string {
  return `${apiConfig.recommenderApiUrl}recommend`;
}

export function getBucketingApiKey(): string {
  return apiConfig.bucketingApiKey;
}

export function getRecommenderApiKey(): string {
  return apiConfig.recommenderApiKey;
}

export function getApiHeaders(
  apiType: 'bucketing' | 'recommender'
): HeadersInit {
  const apiKey =
    apiType === 'bucketing' ? getBucketingApiKey() : getRecommenderApiKey();
  const headers: HeadersInit = { 'Content-Type': 'application/json' };
  if (apiKey && !apiKey.startsWith('__')) {
    headers['x-api-key'] = apiKey;
  }
  return headers;
}
